informulate/talent4startups

app/views/layouts/partials/modal/forms.blade.php, app/views/layouts/partials/nav.blade.php, app/views/layouts/partials/type.blade.php, app/views/registration/select_type.blade.php, public/css/main.css, tests/functional/Registration/StartUpSignUpCept.php, tests/functional/Registration/TalentSignUpCept.php
=> Refactor modal sign up view

app/views/layouts/default.blade.php, app/views/layouts/partials/nav.blade.php, public/css/main.css
=> Change layout from fluid to static

app/Informulate/Forms/StartupForm.php
=> Re #57 added YouTube validation

app/views/layouts/partials/nav.blade.php
Re #46 added link to Knowledge Base
=> Re #46 added link to Knowledge Base

app/Informulate/Users/Profile.php, app/database/migrations/2015_01_18_181250_alter_profile_table.php, app/views/layouts/partials/forms/profile.blade.php
Re #55 profile social media changes
=> Feature 55 profile social media changes

app/Informulate/Startups/Commands/UpdateStartupCommandHandler.php, app/Informulate/Startups/Need.php, app/Informulate/Startups/Startup.php, app/Informulate/Startups/StartupRepository.php, app/assets/sass/_mainpage.scss, app/database/migrations/2015_01_19_043347_add_needs.php, app/database/seeds/StartupTableSeeder.php, app/views/layouts/partials/forms/startup.blade.php, app/views/startups/create.blade.php, app/views/startups/edit.blade.php
* Updated startup create/edit pages with ability to add N number of needs
* Updated startup seeder with new needs data
=> #56 - Create Project - Target Talent

app/assets/sass/_footer.scss, app/assets/sass/main.scss, app/config/app.php, app/config/packages/awjudd/feed-reader/config.php, app/config/packages/thujohn/twitter/config.php, app/controllers/BaseController.php, app/views/layouts/default.blade.php, app/views/layouts/partials/footer.blade.php, composer.json, composer.lock
1. Added packages for RSS feed reader, SimplePie RSS parser, twitter for laravel
2. added footer.blade.php
3. Modified BaseController: added feeds for footer
=> Feature 43 template layout changes

app/views/layouts/partials/nav.blade.php
=> Fix new message icon display

app/controllers/StartupController.php
=> Only allow owners to edit their own startups

app/views/layouts/partials/nav.blade.php
=> Fix active flag on knowledge-base navigation

app/views/layouts/default.blade.php
=> Re #69 Titles

app/config/oauth-4-laravel.php, app/controllers/SessionsController.php, app/views/layouts/partials/modal/forms.blade.php
* Need to setup credentials for beta and production
* Fixes typos on oauth consumer configuration
* Tests user type via query string or in session
* Login needs more work
Dev Complete #89
=> Fix LinkedIn Singup Implementation

app/Informulate/Messenger/Message.php, app/Informulate/Messenger/Thread.php, app/Informulate/Messenger/ThreadRepository.php, app/Informulate/Ratings/Commands/RateUserCommandHandler.php, app/Informulate/Startups/Commands/CancelStartupMembershipRequestCommandHandler.php, app/Informulate/Startups/Events/UserApplied.php, app/Informulate/Startups/Events/UserDenied.php, app/Informulate/Startups/Events/UserJoined.php, app/Informulate/Startups/Events/UserLeft.php, app/Informulate/Startups/StartupRepository.php, app/controllers/MessagesController.php, app/database/migrations/2015_01_26_075234_add_TypeToMessages.php, app/routes.php, app/start/global.php, app/views/layouts/default.blade.php, app/views/messenger/index.blade.php, app/views/messenger/show.blade.php, app/views/messenger/templates/auth/registration.blade.php, app/views/messenger/templates/startup/created/owner.blade.php, app/views/messenger/templates/startup/join/group.blade.php, app/views/messenger/templates/startup/join/invited.blade.php, app/views/messenger/templates/startup/join/request/deny/talent.blade.php, app/views/messenger/templates/startup/join/request/owner.blade.php, app/views/messenger/templates/startup/join/talent.blade.php, app/views/messenger/templates/startup/left/group.blade.php, app/views/messenger/templates/startup/left/talent.blade.php, app/views/messenger/templates/startup/rating/owner.blade.php, app/views/messenger/templates/talent/rating/talent.blade.php, composer.json, composer.lock
Messaging/Notification support
* Added events for users joining/leaving/inviting to startups
* Added method of adding notification to users inbox
* Added listeners for events to trigger notifications
* Templates with subject and body fields for each notification type
* Added type field to messages table for messages and notifications
* Added linkify to composer for auto-linking urls
* Some styling tweaks to messaging
=> Ticket #23 Messaging Copy

app/Informulate/Messenger/Events/NewMessage.php, app/Informulate/Messenger/Message.php, app/Informulate/Messenger/Participant.php, app/Informulate/Messenger/Thread.php, app/Informulate/Messenger/ThreadRepository.php, app/controllers/MessagesController.php, app/start/global.php, app/views/emails/message.blade.php
* Created a new message event
* Created message email template
* Fire new message event with participant information is cleared for participant added
* Listener sends mail
=> Ticket #22 Mandrill Integration

app/Informulate/Users/UserRepository.php, app/controllers/TalentController.php, app/views/startups/index.blade.php, app/views/startups/list.blade.php, app/views/talent/index.blade.php, app/views/talent/list.blade.php
Add location search
Add placeholder text
display warning on empty results
=> Feature 7 display a list of users available as talents

app/assets/sass/_adsense.scss, app/views/layouts/partials/adsense-right.blade.php, app/views/startups/list.blade.php, app/views/talent/list.blade.php
=> Feature 47 google ads

app/database/seeds/StartupTableSeeder.php
* Add missing columns to the seeder
=> Fix database startup seeder

app/Informulate/Forms/RegistrationForm.php
=> Additional registration validations

app/views/profile/edit.blade.php
=> Enhance wording to make it clear how users can update their gravatar

app/views/startups/show.blade.php
=> Prevent non members from rating startups

app/controllers/SessionsController.php
redirects user to appropriate page after authentication
=> Feature 58 authenticated landing page

app/Informulate/Startups/Commands/UpdateStartupCommandHandler.php, app/Informulate/Startups/StartupRepository.php, app/views/layouts/partials/forms/startup.blade.php, app/views/profile/show.blade.php, app/views/startups/edit.blade.php, app/views/startups/list.blade.php, app/views/startups/show.blade.php
=> Ticket #112 startup image uploades"

app/Informulate/Startups/Startup.php, app/Informulate/Startups/StartupRepository.php, app/controllers/ProfileController.php, app/routes.php, app/views/messenger/templates/startup/join/invite/talent.blade.php, app/views/profile/show.blade.php, app/views/startups/show.blade.php
* Fixed stages not saving
* Added startup owner to contributor list
* Changed startup tag search to use needs instead of startup-tags
=>  * Added message and ability to invite users to startups

app/views/profile/show.blade.php, app/views/talent/thumb.blade.php
=> Add rounded circles to uploaded profile pictures

app/Informulate/Users/Profile.php, app/controllers/SessionsController.php, app/views/layouts/partials/forms/profile.blade.php, app/views/pages/home.blade.php
* Prevents incomplete profiles from been published by linkedIn
* Removes static fake ad from the home page
=> Fix an issue with linkedIn registrations

app/listeners.php
=> Fix the use statements on the listener

app/views/talent/thumb.blade.php
=> Changes for demo

app/controllers/PagesController.php, app/routes.php
=> Launch redirect

app/controllers/MessagesController.php
=> Allow messages to be sent to anyone

app/controllers/MessagesController.php, app/views/profile/show.blade.php
=> Prevent emails from been shown on the address bar

app/controllers/SessionsController.php, app/database/migrations/2015_02_24_110412_add_banned_to_users.php
=> Initial banned implementation

app/controllers/MessagesController.php, app/views/profile/show.blade.php
=> Deploy to production

app/controllers/StartupController.php, app/start/global.php, app/views/errors/missing.blade.php
=> Prevent un-published startups from displaying if url is typed

app/Informulate/Messenger/Events/NewMessage.php, app/Informulate/Messenger/Message.php, app/Informulate/Messenger/Participant.php, app/Informulate/Messenger/Thread.php, app/listeners.php, app/views/emails/message.blade.php
=> Fix an issue with messages where participants where not notified

app/controllers/SessionsController.php
* Check for the existance of a user before attempting to see if the user is banned.
=> Fix LinkedIn registration

app/controllers/BaseController.php
=> Feature 140 cache footer feeds

app/Informulate/Startups/StartupRepository.php, app/Informulate/Users/ProfileRepository.php
=> Tags should not be caSe SenSitIve #120

app/controllers/BaseController.php, app/controllers/MembershipController.php, app/controllers/MessagesController.php, app/controllers/PagesController.php, app/controllers/ProfileController.php, app/controllers/RatingController.php, app/controllers/StartupController.php, app/controllers/TalentController.php
=> Prevent incomplete profiles from doing anything else

app/views/layouts/default.blade.php, app/views/pages/home.blade.php
=> Fixes for mobile phones

app/views/layouts/default.blade.php
=> Mobile fixes

app/controllers/BaseController.php, app/controllers/MembershipController.php, app/controllers/StartupController.php, app/database/seeds/StartupTableSeeder.php, app/database/seeds/UserTableSeeder.php
=> Fix startup membershi approval

app/views/startups/show.blade.php
=> Fix requests avatars and links

app/views/startups/show.blade.php
=> Use the proper image

app/views/messenger/index.blade.php, app/views/messenger/show.blade.php, composer.json, composer.lock
Added field labels and friendly status terminology, moved names under thumbnails, moved read/unread buttons
=> Tix #155 - Messaging System Enhancements

app/Events/NewMessage.php
=> Hotfix messaging receiving wrong model

app/Models/Message.php
=> Fix message using wrong event

.env.example, config/mail.php
=> Add email from to the configuration

public/css/main.css, resources/views/startups/thumb.blade.php
1. replace <p> with , on skills list
2. moved more button outside caption div
3. Exposed more of the description
3. adjusted css on caption div, to prevent overflow from colliding with more button
=> fix layout issues in startup blade

resources/views/startups/thumb.blade.php
fix issue object method on object[x]; refactor to a single loop for all values;
=> Feature 209 limit user and startup tags displayed on the thumb section

public/css/main.css, resources/views/talent/thumb.blade.php
=> Fix talents layouts with big descriptions

public/css/main.css, resources/views/talent/thumb.blade.php
=> Fix talent profile image height

resources/views/layouts/partials/forms/profile.blade.php
=> Fix an error when profile is missing for profession

app/Exceptions/Handler.php
=> Don't send to slack if exception is in dont report
